name: Hello
on: workflow_dispatch

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, GitHub Actions!"

  say-bye:
    needs: say-hi
    runs-on: ubuntu-latest
    steps:
      - run: echo "Goodbye, GitHub Actions!"
